import streamlit as st
import pandas as pd
import plotly.express as px
import time
import os

# 1. Page Configuration (Setting wide layout and icon)
st.set_page_config(page_title="Crime Trend Dashboard", page_icon="🚓", layout="wide")

# 2. Header Section
st.title("🚓 Real-time Crime Monitoring System")
#st.markdown("Real-time data streaming simulated via **Kafka** and distributed processing via **PySpark**.")
st.divider() # Adds a neat horizontal line

# Placeholder for continuous updates
placeholder = st.empty()

# Path to the intermediate file generated by Spark
result_file = "data/crime_counts_realtime.csv"

# 3. Real-time Update Loop
while True:
    if os.path.exists(result_file):
        try:
            # Read the calculated results
            df = pd.read_csv(result_file)
            
            # Sort data from highest to lowest count
            df_sorted = df.sort_values(by="count", ascending=False).reset_index(drop=True)
            df_top = df_sorted.head(10)
            
            # Calculate metrics for KPIs
            total_crimes = int(df['count'].sum())
            top_crime_name = df_sorted.iloc[0]['Primary Type'] if not df_sorted.empty else "N/A"
            top_crime_count = int(df_sorted.iloc[0]['count']) if not df_sorted.empty else 0
            
            # Draw the UI inside the placeholder
            with placeholder.container():
                
                # --- SECTION 1: KPI Metrics ---
                kpi1, kpi2, kpi3 = st.columns(3)
                kpi1.metric(label="Total Crimes Processed", value=f"{total_crimes:,}")
                kpi2.metric(label="Most Frequent Crime", value=top_crime_name)
                kpi3.metric(label="Top Crime Count", value=f"{top_crime_count:,}")
                
                st.write("") # Add a little spacing
                
                # --- SECTION 2: Interactive Bar Chart ---
                st.subheader("📊 Top 10 Most Common Crimes")
                
                # Using Plotly for a beautiful, colorful, and interactive chart
                fig = px.bar(
                    df_top,
                    x="Primary Type",
                    y="count",
                    text="count", # Display value on top of bars
                    color="Primary Type", # Give each bar a different color
                    color_discrete_sequence=px.colors.qualitative.Bold
                )
                
                # Tweak chart layout for better aesthetics
                fig.update_traces(textposition='outside', textfont_size=14)
                fig.update_layout(
                    xaxis_title="Crime Category",
                    yaxis_title="Number of Incidents",
                    showlegend=False,
                    margin=dict(l=0, r=0, t=30, b=0),
                    height=450,
                    plot_bgcolor="rgba(0,0,0,0)" # Transparent background
                )
                st.plotly_chart(fig, use_container_width=True)
                
                # --- SECTION 3: Data Table ---
                st.subheader("📋 Detailed Crime Records")
                st.dataframe(
                    df_sorted,
                    use_container_width=True,
                    height=250 # Fix table height so it doesn't push the page down too much
                )
                    
        except Exception as e:
            # Ignore temporary file lock errors when Spark is overwriting the file
            pass 
    else:
        with placeholder.container():
            st.info("⏳ Waiting for Spark to analyze data... Please ensure Kafka and Spark are running.")
            
    # Pause for 2 seconds before redrawing
    time.sleep(2)
    